"""GB-18 acceptance: the backtester's four pricing rules, checked by hand.

The scenario below is worked out independently of the engine — the expected values are
decimal literals derived from the four rulings, not captured from a run. If the engine and
the arithmetic agree, that is evidence; if the literals had been generated by the code
under test, agreement would be a tautology.

The rulings each get their own test, because each one changes every number the study
reports and three of the four are silent when wrong.
"""

from __future__ import annotations

import math
from dataclasses import replace

import numpy as np
import pandas as pd
import pytest
from causality import assert_causal

from glassbox.backtest import engine
from glassbox.config.loader import Config, load_config
from glassbox.contracts.schemas import Signal
from glassbox.engine import risk

SYMBOL = "TEST"
NOTIONAL = 10_000.0


@pytest.fixture
def cfg() -> Config:
    return load_config()


def make_signal(action: str, symbol: str = SYMBOL) -> Signal:
    """Only ``symbol`` and ``action`` matter to the engine; the rest is GB-20's business."""
    return Signal(
        symbol=symbol,
        action=action,
        trend_strength=0.5,
        up_points=3,
        passed_threshold=True,
    )


def fixed_notional(signal: Signal, equity: float, gross_exposure: float, cfg: Config):
    """A test sizer. Real sizing is GB-21; the engine holds no risk logic of its own."""
    del signal, equity, gross_exposure, cfg
    return NOTIONAL


def frame_from(rows: list[tuple[float, float, float, float]]) -> pd.DataFrame:
    index = pd.date_range("2024-01-01", periods=len(rows), freq="B", tz="UTC")
    return pd.DataFrame(
        rows, columns=["open", "high", "low", "close"], index=index, dtype="float64"
    )


# ── the hand-checked three-trade scenario ────────────────────────────────────
#
# Every entry is at a reference price of exactly 100.00, so the arithmetic can be checked
# at a glance. The path is constructed rather than realistic.
#
#  bar  open    high    low     close    what happens
#   0   100.00  100.50   99.50  100.00   enter_long decided at this close
#   1   100.00  101.00   99.00  100.50   ENTRY at the open; exit decided at this close
#   2   102.00  103.00  101.50  102.50   EXIT by signal at the open  -> trade 1
#                                        enter_long decided at this close
#   3   100.00  100.50   98.00   98.50   ENTRY at the open; stop 97.00, target 106.00
#   4    98.00   99.80   96.00   99.50   open 98.00 > stop, low 96.00 <= stop
#                                        -> clean STOP at 97.00  -> trade 2
#                                        enter_long decided at this close
#   5   100.00  100.20   99.50   99.80   ENTRY at the open
#   6    95.00   95.50   94.00   94.50   open 95.00 <= stop -> STOP_GAP at 95.00 -> trade 3
#   7    94.60   95.00   94.00   94.80   flat, final bar

SCENARIO = [
    (100.00, 100.50, 99.50, 100.00),
    (100.00, 101.00, 99.00, 100.50),
    (102.00, 103.00, 101.50, 102.50),
    (100.00, 100.50, 98.00, 98.50),
    (98.00, 99.80, 96.00, 99.50),
    (100.00, 100.20, 99.50, 99.80),
    (95.00, 95.50, 94.00, 94.50),
    (94.60, 95.00, 94.00, 94.80),
]

# Derived from the rulings with 40-digit decimal arithmetic, independently of the engine:
#   fill_in  = p_in  * (1 + s),  shares = 10_000 / fill_in,  fee = shares * fill * f
#   gross    = shares * (p_out - p_in)
#   costs    = shares * s * (p_in + p_out) + fee_in + fee_out
#   net      = gross - costs
# with s = 2 bps and f = 1 bp from settings.yaml.
EXPECTED_SHARES = 99.980003999200
EXPECTED = [
    # entry, exit, gross_pnl, costs, net_pnl, reason
    (100.00, 102.00, 199.9600079984, 6.0587842432, 193.9012237552, engine.SIGNAL),
    (100.00, 97.00, -299.9400119976, 5.9088242352, -305.8488362328, engine.STOP),
    (100.00, 95.00, -499.9000199960, 5.8488402320, -505.7488602280, engine.STOP_GAP),
]
EXPECTED_FINAL_EQUITY = 99382.3035272945

CENT = 0.005


@pytest.fixture
def scenario(cfg: Config) -> engine.BacktestResult:
    bars = frame_from(SCENARIO)
    index = bars.index
    signals = {
        index[0]: [make_signal(engine.ENTER_LONG)],
        index[1]: [make_signal(engine.EXIT)],
        index[2]: [make_signal(engine.ENTER_LONG)],
        index[4]: [make_signal(engine.ENTER_LONG)],
    }
    return engine.run_backtest({SYMBOL: bars}, signals, fixed_notional, cfg)


def test_the_scenario_produces_three_trades(scenario: engine.BacktestResult) -> None:
    assert len(scenario.trades) == 3


@pytest.mark.parametrize("position", range(3), ids=["signal-exit", "stop", "stop-gap"])
def test_each_trade_matches_the_hand_computed_values(
    position: int, scenario: engine.BacktestResult
) -> None:
    """To the cent, and in fact to far more places than a cent."""
    entry, exit_, gross, costs, net, reason = EXPECTED[position]
    trade = scenario.trades[position]

    assert trade.symbol == SYMBOL
    assert trade.exit_reason == reason
    assert trade.entry_price == pytest.approx(entry, abs=CENT)
    assert trade.exit_price == pytest.approx(exit_, abs=CENT)
    assert trade.size == pytest.approx(EXPECTED_SHARES, abs=1e-9)
    assert trade.gross_pnl == pytest.approx(gross, abs=1e-8)
    assert trade.costs == pytest.approx(costs, abs=1e-8)
    assert trade.net_pnl == pytest.approx(net, abs=1e-8)


def test_final_equity_matches_the_hand_computed_total(
    scenario: engine.BacktestResult, cfg: Config
) -> None:
    assert scenario.equity.iloc[-1] == pytest.approx(EXPECTED_FINAL_EQUITY, abs=CENT)
    assert scenario.equity.iloc[0] == pytest.approx(cfg.backtest.initial_cash, abs=CENT)


def test_equity_ends_at_cash_plus_every_net_pnl(
    scenario: engine.BacktestResult, cfg: Config
) -> None:
    """A closed position moves cash by exactly its net PnL. If not, a cost leaked."""
    total = sum(trade.net_pnl for trade in scenario.trades)

    assert scenario.equity.iloc[-1] == pytest.approx(
        cfg.backtest.initial_cash + total, abs=1e-8
    )


def test_net_is_gross_minus_costs_for_every_trade(
    scenario: engine.BacktestResult,
) -> None:
    """An algebraic identity under this decomposition, so it holds exactly or there is a bug."""
    for trade in scenario.trades:
        assert trade.net_pnl == pytest.approx(trade.gross_pnl - trade.costs, abs=1e-9)


def test_the_trade_log_carries_every_required_column(
    scenario: engine.BacktestResult,
) -> None:
    log = scenario.trade_log()

    assert list(log.columns) == [
        "symbol",
        "entry_time",
        "exit_time",
        "size",
        "entry_price",
        "exit_price",
        "gross_pnl",
        "costs",
        "net_pnl",
        "exit_reason",
        "strategy_exit",
    ]
    assert len(log) == 3


# ── ruling 2: a signal fills at the next bar's open ──────────────────────────


def test_entry_fills_at_the_next_open_not_the_signal_bar_close(
    scenario: engine.BacktestResult,
) -> None:
    """Filling at the signal bar's close is the look-ahead GB-10 exists to catch.

    The signal is decided at bar 0's close of 100.00 and bar 1 opens at 100.00 as well, so
    the price alone cannot distinguish the two. The *timestamp* can: the trade must be
    stamped with bar 1, not bar 0.
    """
    index = frame_from(SCENARIO).index

    assert scenario.trades[0].entry_time == index[1]
    assert scenario.trades[0].exit_time == index[2]


def test_a_signal_on_the_final_bar_never_fills(cfg: Config) -> None:
    """There is no next open to fill at, so the order simply expires."""
    bars = frame_from(SCENARIO)
    signals = {bars.index[-1]: [make_signal(engine.ENTER_LONG)]}

    result = engine.run_backtest({SYMBOL: bars}, signals, fixed_notional, cfg)

    assert result.trades == ()


# ── ruling 4: gaps fill at the open ──────────────────────────────────────────


def test_a_clean_stop_fills_at_the_stop_not_the_close(
    scenario: engine.BacktestResult,
) -> None:
    """Bar 4 closes at 99.50 having traded down to 96.00. The exit is the stop, 97.00."""
    stop_trade = scenario.trades[1]

    assert stop_trade.exit_reason == engine.STOP
    assert stop_trade.exit_price == pytest.approx(97.00, abs=CENT)


def test_a_gapped_stop_fills_at_the_open_not_the_stop(
    scenario: engine.BacktestResult,
) -> None:
    """Bar 6 opens at 95.00, already through the 97.00 stop, which was never available."""
    gapped = scenario.trades[2]

    assert gapped.exit_reason == engine.STOP_GAP
    assert gapped.exit_price == pytest.approx(95.00, abs=CENT)
    assert gapped.exit_price < 97.00


def test_a_target_exit_fills_at_the_target(cfg: Config) -> None:
    """The comparison the reference project inverts: the HIGH rising to the target."""
    bars = frame_from(
        [
            (100.00, 100.50, 99.50, 100.00),
            (100.00, 101.00, 99.00, 100.50),
            (101.00, 107.00, 100.50, 106.50),  # high 107 >= target 106, open below it
        ]
    )
    signals = {bars.index[0]: [make_signal(engine.ENTER_LONG)]}

    result = engine.run_backtest({SYMBOL: bars}, signals, fixed_notional, cfg)

    assert len(result.trades) == 1
    assert result.trades[0].exit_reason == engine.TARGET
    assert result.trades[0].exit_price == pytest.approx(106.00, abs=CENT)


def test_a_gapped_target_fills_at_the_open(cfg: Config) -> None:
    bars = frame_from(
        [
            (100.00, 100.50, 99.50, 100.00),
            (100.00, 101.00, 99.00, 100.50),
            (108.00, 109.00, 107.50, 108.50),  # opens above the 106.00 target
        ]
    )
    signals = {bars.index[0]: [make_signal(engine.ENTER_LONG)]}

    result = engine.run_backtest({SYMBOL: bars}, signals, fixed_notional, cfg)

    assert result.trades[0].exit_reason == engine.TARGET_GAP
    assert result.trades[0].exit_price == pytest.approx(108.00, abs=CENT)


# ── ruling 1: the stop wins an ambiguous bar ─────────────────────────────────


def test_a_bar_breaching_both_levels_exits_at_the_stop(cfg: Config) -> None:
    """Daily OHLC cannot say which came first, so the conservative reading is pinned here.

    Measured across the real universe, this decides 0.08% of resolutions — which is the
    argument for taking it, not against: the objection it removes is free.
    """
    bars = frame_from(
        [
            (100.00, 100.50, 99.50, 100.00),
            (100.00, 101.00, 99.00, 100.50),
            (
                100.00,
                107.00,
                96.00,
                103.00,
            ),  # low 96 <= 97 stop AND high 107 >= 106 target
        ]
    )
    signals = {bars.index[0]: [make_signal(engine.ENTER_LONG)]}

    result = engine.run_backtest({SYMBOL: bars}, signals, fixed_notional, cfg)

    assert result.trades[0].exit_reason == engine.STOP
    assert result.trades[0].exit_price == pytest.approx(97.00, abs=CENT)
    assert result.trades[0].net_pnl < 0


# ── ruling 3: costs, twice per round trip ────────────────────────────────────


def test_a_flat_round_trip_costs_exactly_the_configured_bps(cfg: Config) -> None:
    """Both legs pay slippage and both pay a fee, so a flat trade costs 2*(fee+slippage).

    Asserted against the engine's own numbers rather than against arithmetic in a
    docstring, and cross-checked against ``round_trip_cost_bps``.
    """
    bars = frame_from(
        [
            (100.00, 100.20, 99.80, 100.00),
            (100.00, 100.20, 99.80, 100.00),
            (
                100.00,
                100.20,
                99.80,
                100.00,
            ),  # exits by signal at exactly the entry price
        ]
    )
    signals = {
        bars.index[0]: [make_signal(engine.ENTER_LONG)],
        bars.index[1]: [make_signal(engine.EXIT)],
    }

    trade = engine.run_backtest({SYMBOL: bars}, signals, fixed_notional, cfg).trades[0]
    reference_notional = trade.size * trade.entry_price

    assert trade.gross_pnl == pytest.approx(0.0, abs=1e-9)
    assert trade.costs / reference_notional * 10_000 == pytest.approx(6.0, abs=1e-9)
    assert engine.round_trip_cost_bps(cfg) == pytest.approx(6.0, abs=1e-12)


def test_costs_are_applied_on_both_legs(cfg: Config) -> None:
    """Halve the trip and the cost halves: proof the charge is per leg, not per trade."""
    entry_only = replace(cfg, backtest=replace(cfg.backtest, fee_bps=0.0))
    bars = frame_from([(100.00, 100.20, 99.80, 100.00)] * 3)
    signals = {
        bars.index[0]: [make_signal(engine.ENTER_LONG)],
        bars.index[1]: [make_signal(engine.EXIT)],
    }

    with_fees = engine.run_backtest(
        {SYMBOL: bars}, signals, fixed_notional, cfg
    ).trades[0]
    without = engine.run_backtest(
        {SYMBOL: bars}, signals, fixed_notional, entry_only
    ).trades[0]
    fee_component = with_fees.costs - without.costs
    one_leg = with_fees.size * with_fees.entry_price * cfg.backtest.fee_bps / 10_000

    assert fee_component == pytest.approx(2 * one_leg, rel=1e-6)


# ── causality ────────────────────────────────────────────────────────────────


def long_series(bars: int = 200) -> pd.DataFrame:
    """A wandering price path long enough for three split points."""
    index = pd.date_range("2020-01-01", periods=bars, freq="B", tz="UTC")
    close = pd.Series(
        [
            100.0 + 8.0 * math.sin(i / 9.0) + 3.0 * math.cos(i / 2.7)
            for i in range(bars)
        ],
        index=index,
    )
    return pd.DataFrame(
        {
            "open": close.shift(1).fillna(close.iloc[0]),
            "high": close * 1.012,
            "low": close * 0.988,
            "close": close,
        }
    )


def test_perturbing_future_bars_leaves_past_equity_untouched(cfg: Config) -> None:
    """The property the whole module is arranged around, asserted with GB-10's harness.

    Both perturbation modes run: `scale` catches an equity point that reads a future
    price level, `shuffle` catches one that depends on the order of bars still to come.
    """
    bars = long_series()
    signals = {
        timestamp: [make_signal(engine.ENTER_LONG if step % 2 == 0 else engine.EXIT)]
        for step, timestamp in enumerate(bars.index[::7])
    }

    def equity_of(frame: pd.DataFrame) -> pd.Series:
        return engine.run_backtest({SYMBOL: frame}, signals, fixed_notional, cfg).equity

    equity_of.__name__ = "run_backtest().equity"
    assert_causal(equity_of, bars)


def test_the_equity_curve_is_ordered_and_complete(
    scenario: engine.BacktestResult,
) -> None:
    equity = scenario.equity

    assert equity.index.is_monotonic_increasing
    assert equity.index.is_unique
    assert len(equity) == len(SCENARIO)
    assert not equity.isna().any()
    assert np.isfinite(equity.to_numpy()).all()


# ── the sizing interface ─────────────────────────────────────────────────────


def test_a_sizer_asking_for_more_than_the_cash_is_refused(cfg: Config) -> None:
    """GB-21 promises no over-limit position. The engine holds it to that."""

    def greedy(signal, equity, gross_exposure, cfg):
        del signal, equity, gross_exposure
        return cfg.backtest.initial_cash * 2

    bars = frame_from(SCENARIO)
    signals = {bars.index[0]: [make_signal(engine.ENTER_LONG)]}

    with pytest.raises(ValueError, match="may not trade on margin"):
        engine.run_backtest({SYMBOL: bars}, signals, greedy, cfg)


def test_a_negative_notional_is_refused(cfg: Config) -> None:
    def short_seller(signal, equity, gross_exposure, cfg):
        del signal, equity, gross_exposure, cfg
        return -1000.0

    bars = frame_from(SCENARIO)
    signals = {bars.index[0]: [make_signal(engine.ENTER_LONG)]}

    with pytest.raises(ValueError, match="long-only"):
        engine.run_backtest({SYMBOL: bars}, signals, short_seller, cfg)


def test_a_zero_notional_means_no_trade(cfg: Config) -> None:
    def declines(signal, equity, gross_exposure, cfg):
        del signal, equity, gross_exposure, cfg
        return 0.0

    bars = frame_from(SCENARIO)
    signals = {bars.index[0]: [make_signal(engine.ENTER_LONG)]}

    result = engine.run_backtest({SYMBOL: bars}, signals, declines, cfg)

    assert result.trades == ()
    assert result.equity.nunique() == 1


def test_the_sizer_sees_exposure_marked_at_the_previous_close(cfg: Config) -> None:
    """An order filling at bar t's open must be sized without reading bar t's close.

    This is the reference project's look-ahead in its subtlest form. It survived GB-18
    because every sizer in that task's tests ignored ``equity`` and ``gross_exposure``
    entirely, so nothing observed which price the exposure was marked at. The sizer here
    does consult them, and the two hypotheses are 240 basis points apart on purpose.

    A position is opened in HELD on day 1. On day 3 a second entry is sized, and at that
    moment HELD's *last printed close* is day 2's 100.60 while day 3's own close is
    103.00 — a bar that, at the open, has not happened yet.
    """
    seen: list[tuple[float, float]] = []

    def recording(signal, equity, gross_exposure, cfg):
        del signal, cfg
        seen.append((equity, gross_exposure))
        return NOTIONAL

    held = frame_from(
        [
            (100.00, 100.50, 99.50, 100.00),  # 0  enter_long decided at this close
            (100.00, 100.60, 99.60, 100.20),  # 1  ENTRY at 100.00
            (100.50, 100.80, 100.00, 100.60),  # 2  close 100.60 — the honest mark
            (102.00, 103.50, 101.80, 103.00),  # 3  close 103.00 — the look-ahead value
            (103.00, 103.20, 102.50, 103.00),
            (103.00, 103.20, 102.50, 103.00),
        ]
    )
    bars = {SYMBOL: held, "OTHER": frame_from([(100.00, 100.20, 99.80, 100.00)] * 6)}
    signals = {
        held.index[0]: [make_signal(engine.ENTER_LONG)],
        held.index[2]: [make_signal(engine.ENTER_LONG, "OTHER")],  # sized on day 3
    }

    engine.run_backtest(bars, signals, recording, cfg)

    assert len(seen) == 2
    _, exposure = seen[1]
    at_previous_close = EXPECTED_SHARES * 100.60
    at_this_bars_close = EXPECTED_SHARES * 103.00

    assert exposure == pytest.approx(at_previous_close, abs=CENT)
    assert exposure != pytest.approx(at_this_bars_close, abs=CENT)


def test_the_sizer_sees_equity_and_exposure(cfg: Config) -> None:
    """The interface GB-21 implements, pinned so it cannot drift before it is written."""
    seen: list[tuple[float, float]] = []

    def recording(signal, equity, gross_exposure, cfg):
        del signal, cfg
        seen.append((equity, gross_exposure))
        return NOTIONAL

    bars = frame_from(SCENARIO)
    signals = {
        bars.index[0]: [make_signal(engine.ENTER_LONG)],
        bars.index[2]: [make_signal(engine.ENTER_LONG)],
    }
    engine.run_backtest({SYMBOL: bars}, signals, recording, cfg)

    assert seen
    first_equity, first_exposure = seen[0]
    assert first_equity == pytest.approx(cfg.backtest.initial_cash, abs=CENT)
    assert first_exposure == pytest.approx(0.0, abs=1e-9)


# ── position bookkeeping ─────────────────────────────────────────────────────


def test_a_second_entry_signal_does_not_pyramid(cfg: Config) -> None:
    """The reference project overwrites the open position and leaks the old one."""
    bars = frame_from(SCENARIO)
    signals = {
        bars.index[0]: [make_signal(engine.ENTER_LONG)],
        bars.index[1]: [make_signal(engine.ENTER_LONG)],
    }

    result = engine.run_backtest({SYMBOL: bars}, signals, fixed_notional, cfg)

    assert len({trade.entry_time for trade in result.trades}) == len(result.trades)
    assert result.trades[0].size == pytest.approx(EXPECTED_SHARES, abs=1e-9)


def test_a_closed_position_stops_being_checked(cfg: Config) -> None:
    """The reference project never clears `position`, so its stop re-fires forever."""
    bars = frame_from(SCENARIO)
    signals = {bars.index[2]: [make_signal(engine.ENTER_LONG)]}

    result = engine.run_backtest({SYMBOL: bars}, signals, fixed_notional, cfg)

    assert len(result.trades) == 1
    assert result.trades[0].exit_reason == engine.STOP


def test_an_open_position_is_liquidated_at_the_final_close(cfg: Config) -> None:
    bars = frame_from(SCENARIO[:3])
    signals = {bars.index[0]: [make_signal(engine.ENTER_LONG)]}

    result = engine.run_backtest({SYMBOL: bars}, signals, fixed_notional, cfg)

    assert result.trades[-1].exit_reason == engine.END_OF_DATA
    assert result.trades[-1].exit_price == pytest.approx(SCENARIO[2][3], abs=CENT)


# ── share granularity, shared with GB-22's executor ──────────────────────────


def test_the_engine_converts_notional_through_the_shared_function(cfg: Config) -> None:
    """One conversion, used by the backtester and by GB-22's live executor.

    If the backtest bought 99.98 shares and the executor floored to 99, the two systems
    would describe different things and every test would still pass — the failure family
    GB-7's RAW adjustment belongs to.
    """
    trade = None
    bars = frame_from(SCENARIO)
    signals = {bars.index[0]: [make_signal(engine.ENTER_LONG)]}
    trade = engine.run_backtest({SYMBOL: bars}, signals, fixed_notional, cfg).trades[0]

    fill = trade.entry_price * (1 + cfg.backtest.slippage_bps / 10_000)

    assert trade.size == pytest.approx(risk.shares_for(NOTIONAL, fill), abs=1e-12)


def test_shares_are_fractional_not_floored() -> None:
    """Flooring would discretise a percentage-of-equity rule by price level."""
    assert risk.shares_for(1000.0, 300.0) == pytest.approx(1000.0 / 300.0, abs=1e-12)
    assert risk.shares_for(1000.0, 300.0) != math.floor(1000.0 / 300.0)


def test_a_notional_below_the_brokers_minimum_places_no_order(cfg: Config) -> None:
    """The broker would reject it, so filling it in a backtest invents a trade."""
    assert risk.shares_for(0.0001, 1000.0) == 0.0

    def dust(signal, equity, gross_exposure, cfg):
        del signal, equity, gross_exposure, cfg
        return 0.01  # 0.0001 shares at a price of 100

    bars = frame_from(SCENARIO)
    signals = {bars.index[0]: [make_signal(engine.ENTER_LONG)]}

    assert engine.run_backtest({SYMBOL: bars}, signals, dust, cfg).trades == ()


def test_shares_for_refuses_a_non_positive_price() -> None:
    with pytest.raises(ValueError, match="price must be positive"):
        risk.shares_for(1000.0, 0.0)


# ── administrative exits ─────────────────────────────────────────────────────


def test_an_administrative_exit_is_flagged_not_string_matched(cfg: Config) -> None:
    """GB-19 filters on the boolean; `exit_reason` stays a human-readable label."""
    bars = frame_from(SCENARIO[:3])
    signals = {bars.index[0]: [make_signal(engine.ENTER_LONG)]}

    result = engine.run_backtest({SYMBOL: bars}, signals, fixed_notional, cfg)

    assert result.trades[-1].exit_reason == engine.END_OF_DATA
    assert result.trades[-1].strategy_exit is False


def test_every_decided_exit_is_flagged_as_one(scenario: engine.BacktestResult) -> None:
    assert all(trade.strategy_exit for trade in scenario.trades)
    assert {trade.exit_reason for trade in scenario.trades} == {
        engine.SIGNAL,
        engine.STOP,
        engine.STOP_GAP,
    }


def test_an_administrative_exit_still_moves_the_equity_curve(cfg: Config) -> None:
    """Included in total return — the capital really was returned — but not a decision."""
    bars = frame_from(SCENARIO[:3])
    signals = {bars.index[0]: [make_signal(engine.ENTER_LONG)]}

    result = engine.run_backtest({SYMBOL: bars}, signals, fixed_notional, cfg)
    liquidation = result.trades[-1]

    assert liquidation.net_pnl != 0.0
    assert result.equity.iloc[-1] == pytest.approx(
        cfg.backtest.initial_cash + liquidation.net_pnl, abs=1e-8
    )


def test_two_symbols_share_one_equity_curve(cfg: Config) -> None:
    """The portfolio is the unit: the curve is cash plus every position, not a per-symbol sum."""
    bars = {SYMBOL: frame_from(SCENARIO), "OTHER": frame_from(SCENARIO)}
    index = bars[SYMBOL].index
    signals = {
        index[0]: [
            make_signal(engine.ENTER_LONG),
            make_signal(engine.ENTER_LONG, "OTHER"),
        ]
    }

    result = engine.run_backtest(bars, signals, fixed_notional, cfg)

    assert {trade.symbol for trade in result.trades} == {SYMBOL, "OTHER"}
    assert len(result.equity) == len(SCENARIO)


# ── ruling 5: a missing bar is a halt, not an exit ───────────────────────────
#
# These tests exist because of a real defect, and the numbers below are the damage it
# did rather than an illustration of what it might have done. In both cases the engine
# popped the position from its book before checking whether the symbol had a price that
# day; when there was none, the holding vanished, cash was never credited, and no trade was
# logged. Measured on the committed engine, each case deleted **10,001.00 of a 100,000
# account - 10.0% - with an empty trade log**. The second case is not exotic: it fires
# whenever one symbol's history ends before the universe's does.

HALT_INDEX = pd.date_range("2024-01-01", periods=6, freq="B", tz="UTC")
FLAT_BARS = [(100.00, 100.20, 99.80, 100.00)] * 6

# Days 0, 1, 2, 4, 5 — the symbol does not trade on day 3.
HALTED_BARS = [
    (100.00, 100.50, 99.50, 100.00),  # 0  enter_long decided at this close
    (100.00, 100.60, 99.60, 100.20),  # 1  ENTRY at 100.00; stop 97.00, target 106.00
    (100.50, 100.80, 100.00, 100.60),  # 2  exit decided at this close
    # 3  no bar: the exit cannot fill, and the position is marked at 100.60
    (101.00, 101.50, 100.80, 101.20),  # 4  the carried exit fills at this open, 101.00
    (101.20, 101.60, 101.00, 101.40),  # 5
]

# Days 0..3 only, against a universe that runs to day 5.
SHORT_HISTORY_BARS = [
    (100.00, 100.50, 99.50, 100.00),  # 0  enter_long decided at this close
    (100.00, 100.60, 99.60, 100.20),  # 1  ENTRY at 100.00
    (100.50, 100.80, 100.00, 100.60),  # 2
    (100.80, 101.00, 100.40, 100.90),  # 3  the last bar this symbol ever prints
]


def frame_on(rows: list[tuple[float, float, float, float]], days: tuple[int, ...]):
    """A frame on a subset of the shared index, so the master index has gaps in it."""
    return pd.DataFrame(
        rows,
        columns=["open", "high", "low", "close"],
        index=HALT_INDEX[list(days)],
        dtype="float64",
    )


@pytest.fixture
def halted(cfg: Config) -> engine.BacktestResult:
    bars = {
        SYMBOL: frame_on(HALTED_BARS, (0, 1, 2, 4, 5)),
        "OTHER": frame_on(FLAT_BARS, (0, 1, 2, 3, 4, 5)),
    }
    signals = {
        HALT_INDEX[0]: [make_signal(engine.ENTER_LONG)],
        HALT_INDEX[2]: [make_signal(engine.EXIT)],
    }
    return engine.run_backtest(bars, signals, fixed_notional, cfg)


@pytest.fixture
def short_history(cfg: Config) -> engine.BacktestResult:
    bars = {
        SYMBOL: frame_on(SHORT_HISTORY_BARS, (0, 1, 2, 3)),
        "OTHER": frame_on(FLAT_BARS, (0, 1, 2, 3, 4, 5)),
    }
    signals = {HALT_INDEX[0]: [make_signal(engine.ENTER_LONG)]}
    return engine.run_backtest(bars, signals, fixed_notional, cfg)


def test_an_exit_on_a_day_with_no_bar_keeps_the_position(
    halted: engine.BacktestResult,
) -> None:
    """The order is carried to the symbol's next traded open and logged there.

    A halt is not a fill. Dropping the position here deleted 10,001.00 of a 100,000
    account and logged nothing.
    """
    assert len(halted.trades) == 1
    trade = halted.trades[0]

    assert trade.exit_reason == engine.SIGNAL
    assert trade.exit_time == HALT_INDEX[4]  # not day 3, which the symbol did not trade
    assert trade.exit_price == pytest.approx(101.00, abs=CENT)


def test_a_halted_position_is_marked_at_its_own_last_close(
    halted: engine.BacktestResult,
) -> None:
    """On the untraded day the holding is worth its last print, not its entry price.

    Marking at the entry price is the second half of the same defect: it moved the curve
    by 60 basis points of the position on a day nothing happened.
    """
    cash_after_entry = 89_999.00  # 100_000 - 10_000 notional - 1.00 entry fee
    at_last_close = cash_after_entry + EXPECTED_SHARES * 100.60
    at_entry_price = cash_after_entry + EXPECTED_SHARES * 100.00

    assert halted.equity.iloc[3] == pytest.approx(at_last_close, abs=CENT)
    assert halted.equity.iloc[3] != pytest.approx(at_entry_price, abs=CENT)


def test_an_entry_on_a_day_with_no_bar_expires_rather_than_carrying(
    cfg: Config,
) -> None:
    """The asymmetry with the exit above, pinned rather than left to be inferred.

    An entry is a bet on a forecast from a window ending at a particular bar; by the time
    the symbol trades again the forecast is stale, and a live loop would recompute it
    rather than resurrect the order. An exit is an obligation on capital already at risk.
    """
    bars = {
        SYMBOL: frame_on(HALTED_BARS, (0, 1, 2, 4, 5)),
        "OTHER": frame_on(FLAT_BARS, (0, 1, 2, 3, 4, 5)),
    }
    signals = {HALT_INDEX[2]: [make_signal(engine.ENTER_LONG)]}  # acts on day 3: no bar

    result = engine.run_backtest(bars, signals, fixed_notional, cfg)

    assert result.trades == ()  # it did not resurface on day 4
    assert result.equity.iloc[-1] == pytest.approx(cfg.backtest.initial_cash, abs=CENT)


def test_a_symbol_ending_early_liquidates_at_its_own_last_close(
    short_history: engine.BacktestResult,
) -> None:
    """Day 3's close, stamped with day 3 — not day 5, where this symbol has no price."""
    assert len(short_history.trades) == 1
    trade = short_history.trades[0]

    assert trade.exit_reason == engine.END_OF_DATA
    assert trade.strategy_exit is False
    assert trade.exit_price == pytest.approx(100.90, abs=CENT)
    assert trade.exit_time == HALT_INDEX[3]


@pytest.mark.parametrize("case", ["halted", "short_history"])
def test_both_halt_cases_end_at_cash_plus_every_net_pnl(
    case: str, cfg: Config, request: pytest.FixtureRequest
) -> None:
    """The identity the defect broke, asserted on both of the cases that broke it.

    On the committed engine each of these ended at 89,999.00 against an expected
    100,000.00 — a gap of exactly the position's notional plus its entry fee.
    """
    result: engine.BacktestResult = request.getfixturevalue(case)
    total = sum(trade.net_pnl for trade in result.trades)

    assert result.equity.iloc[-1] == pytest.approx(
        cfg.backtest.initial_cash + total, abs=1e-8
    )
    assert result.equity.iloc[-1] > cfg.backtest.initial_cash * 0.99


def test_the_accounting_invariant_runs_on_every_backtest(cfg: Config) -> None:
    """Not a test-only assertion: it guards the module in ordinary use.

    Proven to have teeth by handing it a curve that does not reconcile — if it accepted
    that, it would have accepted the 10,001.00 gap too.
    """
    trade = engine.Trade(
        symbol=SYMBOL,
        entry_time=HALT_INDEX[0],
        exit_time=HALT_INDEX[1],
        size=1.0,
        entry_price=100.0,
        exit_price=101.0,
        gross_pnl=1.0,
        costs=0.0,
        net_pnl=1.0,
        exit_reason=engine.SIGNAL,
        strategy_exit=True,
    )

    engine._assert_accounted(cfg.backtest.initial_cash + 1.0, {}, [trade], cfg)

    with pytest.raises(AssertionError, match="without a trade recording it"):
        engine._assert_accounted(cfg.backtest.initial_cash - 10_001.0, {}, [trade], cfg)


# ── input validation ─────────────────────────────────────────────────────────


def test_empty_bars_are_refused(cfg: Config) -> None:
    with pytest.raises(ValueError, match="no bars"):
        engine.run_backtest({}, {}, fixed_notional, cfg)


def test_a_missing_column_is_refused(cfg: Config) -> None:
    bars = frame_from(SCENARIO).drop(columns=["low"])

    with pytest.raises(ValueError, match="low"):
        engine.run_backtest({SYMBOL: bars}, {}, fixed_notional, cfg)


def test_unsorted_bars_are_refused(cfg: Config) -> None:
    bars = frame_from(SCENARIO).iloc[::-1]

    with pytest.raises(ValueError, match="sorted"):
        engine.run_backtest({SYMBOL: bars}, {}, fixed_notional, cfg)
